import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#2d486d",
        "outline-variant": "#c4c6cf",
        "on-surface-variant": "#43474e",
        "primary-container": "#1e3a5f",
        "secondary-container": "#86f2e4",
        "tertiary-fixed-dim": "#ffb95f",
        "surface": "#f7f9fb",
        "on-surface": "#191c1e",
        "secondary": "#006a61",
        "on-secondary-fixed-variant": "#005049",
        "tertiary-fixed": "#ffddb8",
        "surface-container-highest": "#e0e3e5",
        "primary-fixed": "#d5e3ff",
        "surface-variant": "#e0e3e5",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#6bd8cb",
        "on-primary": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "inverse-primary": "#adc8f5",
        "primary-fixed-dim": "#adc8f5",
        "on-primary-container": "#8aa4cf",
        "on-primary-fixed": "#001c3b",
        "on-secondary-fixed": "#00201d",
        "background": "#f7f9fb",
        "inverse-surface": "#2d3133",
        "tertiary": "#361f00",
        "on-background": "#191c1e",
        "surface-tint": "#455f87",
        "surface-dim": "#d8dadc",
        "tertiary-container": "#533200",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#653e00",
        "on-error-container": "#93000a",
        "secondary-fixed": "#89f5e7",
        "surface-container-low": "#f2f4f6",
        "inverse-on-surface": "#eff1f3",
        "surface-bright": "#f7f9fb",
        "on-secondary-container": "#006f66",
        "outline": "#74777f",
        "on-tertiary-container": "#e39100",
        "surface-container": "#eceef0",
        "primary": "#022448",
        "on-tertiary-fixed": "#2a1700",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
